# Generated by Django 6.0.2 on 2026-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True, default="", upload_to="books/covers/"
            ),
        ),
    ]
