docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "docker-compose.yml"
          - "Dockerfile"

test:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
