name: Setup Python Environment
description: Install uv, restore venv cache, and sync dependencies

inputs:
  python-version:
    description: Python version to install
    required: true

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
        restore-keys: venv-${{ runner.os }}-${{ inputs.python-version }}-
    - run: uv sync --dev
      shell: bash
