name: Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: aquasecurity/trivy-action@2736533278103862a861f4a35ebac3e97854d956 # master
        with:
          scan-type: "config"
          scan-ref: "."
          trivy-config: trivy.yaml
