name: Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: aquasecurity/trivy-action@df678dbccf677bc6937338d569ba0da18964a8cc # master
        with:
          scan-type: "config"
          scan-ref: "."
          trivy-config: trivy.yaml
